// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAV8cyf7883UdFoc3u3BEeOuyfWC1L194Q',
    appId: '1:654626843466:web:7997cf3e327e9e74d56fb3',
    messagingSenderId: '654626843466',
    projectId: 'circle-83755',
    authDomain: 'circle-83755.firebaseapp.com',
    storageBucket: 'circle-83755.appspot.com',
    measurementId: 'G-1SDF79WYN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKt3yTL1vE8Fcnny3rKo4HXqPZJZ0uNP0',
    appId: '1:654626843466:android:1bcc3b6f4984feaad56fb3',
    messagingSenderId: '654626843466',
    projectId: 'circle-83755',
    storageBucket: 'circle-83755.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIbiyRO9-egGpWXBudyAw2XTFE7XRS5zQ',
    appId: '1:654626843466:ios:5838aca8282a5e00d56fb3',
    messagingSenderId: '654626843466',
    projectId: 'circle-83755',
    storageBucket: 'circle-83755.appspot.com',
    iosClientId: '654626843466-8dbu305k0ouq9o7tl0buqd3pkupccgcr.apps.googleusercontent.com',
    iosBundleId: 'com.example.circle',
  );
}
